# Generated by Django 2.0.5 on 2018-05-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=3000)),
                ('Time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=3000)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=1000)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Info', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restnumber', models.IntegerField(default=0)),
                ('Time', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Doctorid', models.IntegerField(default=0)),
                ('Phonenumber', models.IntegerField(default=0)),
                ('Password', models.CharField(max_length=30)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phonenumber', models.IntegerField(default=0)),
                ('Info', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=2000)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.District')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=1000)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Tag', models.CharField(max_length=50)),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(max_length=20)),
                ('Phonenumber', models.IntegerField(default=0)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NP', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Info', models.CharField(max_length=2000)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Department')),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital')),
                ('Patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patients')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='Register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Register'),
        ),
        migrations.AddField(
            model_name='message',
            name='Patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patients'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='departmentlist',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patients'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patients'),
        ),
    ]
